apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarq-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: sonarqube
      labels:
        name: sonarqube
    spec:
      containers:
        - image: registry.eu-de.bluemix.net/sonarq-namespace/sonarqube:1
          name: sonarqube-container
          env:
          - name: SONARQUBE_JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                name: sonarq-secret
                key: username
          - name: SONARQUBE_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sonarq-secret
                key: password
          - name: SONARQUBE_JDBC_URL
            valueFrom:
              configMapKeyRef:
                name: sonarq-config
                key: DB_URL
          ports:
            - containerPort: 9000
              name: sonarq-port
