@startuml
header
<b>Full BIM / VAMP : Lot 5 Hyperviseur</b>- Diagramme de contexte
end header

(BEYOND - **Platform** ) as SYSTEM

:Administrateur technique: as ACTOR2 <<human>>
:Administrateur 'Métier': as ACTOR3 <<human>>
:Administrateur "Utilisateurs": as ACTOR4 <<human>>
:Utilisateur final: as ACTOR5 <<human>>
:Utilisateur anonyme: as ACTOR6 <<human>>

:CUSTOMER - **Identity provider**: as SYSTEM2<<system>>
:CUSTOMER - **Data and Service providers**: as SYSTEM3<<system>>
:CUSTOMER - **Data and Service Consumers**: as SYSTEM4<<system>>
:BEYOND/Sixense - **Identity provider**: as SYSTEM5 <<system>>

ACTOR2  ---|>SYSTEM
ACTOR3  --|>SYSTEM
ACTOR4  ---|>SYSTEM
ACTOR5  --|>SYSTEM
ACTOR6  ---|>SYSTEM


SYSTEM <|--- SYSTEM2
SYSTEM <|-- SYSTEM3
SYSTEM <|-- SYSTEM4
SYSTEM <|--- SYSTEM5



@enduml
