@startuml
header
<b>BEYOND Platform </b>- Modèle de cas d'utilisation - Acteurs
end header

Rectangle "HUMAINS" as HUMAINS  {



Package "Fournisseur du Service"  as SRVPROVUSR #LightSteelBlue{
 :Administrateur technique: as ACTOR2 <<human>>
}
Package "Tenant/Client du Service "  as CLIENTUSR{
:Administrateur 'Métier': as ACTOR3 <<human>>
:Utilisateur final: as ACTOR5 <<human>> 
}
:Utilisateur anonyme: as ACTOR6 <<human>>
}
@enduml
