@startuml enrichment_update

title

Beyond Manager : Mette à jour un enrichissement

end title

|#AntiqueWhite| Front |
start
->  **Hypothèse:** \n  - Utilisateur authentifié \n  - Profil Utilisateur BEYOND:  \n    - accéder ;

-Être sur Beyond Manager, \n- cliquer sur "Enrichissement" dans la sidebar de gauche
-Ouverture de l'interface enrichissement
-Sélectionner l'enrichissement que l'on veut supprimer \nCliquer sur le bouton **Poubelle** à droite \n\nUne popup de confirmation apparait, valider avec \nle bouton "**Suppimer**"

| Back |
note right
  api "PUT **/enrichment/:id**"
end note
if ( \n Vérifier les droits \n **access** \n)
-[#red]-> Non ;
-Retour du code erreur \n **401: UNAUTHORIZED**
stop

elseif ( \n Body valide \n **JSON Schema** \n )
-[#red]-> Non ;
-Retour du code erreur \n **406: BODY_ERROR**
stop
endif

partition "Validation de l'enrichissement" {
    if ( \n Template existe\n )
    -[#red]-> Non ;
    -Retour du code erreur \n **400: TEMPLATE_NOTEXIST**
    stop
    elseif ( \n Propriété valide avec le template \n JSON Schema \n )
    -[#red]-> Non ;
    -Retour du code erreur \n **406: BODY_ERROR**
    stop

    elseif ( \n Erreur interne \n )
    -[#red]-> Oui ;
    -Retour du code erreur \n **500: INTERNAL_ERROR**
    stop
    endif
}

partition "Mise à jour de \nl'enrichissement" {
    -Génération du REVISIONID
    note right
      Pas encore implémenté
    end note
    - Mise à jour de l'enrichissement \n templateId \n templateLabel \n idcardId \n idcardRevisionId \n Propriétaire \n ...;
    if ( \n Ecriture OK \n )
    -[#green]-> Oui ;
    -Retour du code \n **200: SUCCESS**
    else
    -[#red]-> Non ;
    -Retour du code erreur \n **500: INTERNAL_ERROR**
    endif
}
stop

legend 
**Légende**

**Retour du code erreur** : Permet la remontée d'un message d'erreur (localisé) à l'utilisateur.

endlegend

@enduml
