@startuml

title
POST **/enrichment/** : Créer un enrichissement

end title

start
if ( \n Vérifier les droits \n **access** \n)
-[#red]-> Non ;
-Retour du code erreur \n **401: UNAUTHORIZED**
stop

elseif ( \n Valide body \n **JSON Schema** \n )
-[#red]-> Non ;
-Retour du code erreur \n **406: BODY_ERROR**
stop

elseif ( \n Idcard existe \n )
-[#red]-> Non ;
-Retour du code erreur \n **400: ID_NOTVALID**
stop

elseif ( \n Vérifer s'il est déjà présent en base \n )
-[#red]-> Oui ;
-Retour du code erreur \n **400: ENRICHMENT_ALREADYEXIST**
stop
endif

partition "Validation de l'enrichissement" {
    if ( \n Template existe\n )
    -[#red]-> Non ;
    -Retour du code erreur \n **400: TEMPLATE_NOTEXIST**
    stop

    elseif ( \n Propriété valide avec le template \n JSON Schema \n )
    -[#red]-> Non ;
    -Retour du code erreur \n **406: BODY_ERROR**
    stop

    elseif ( \n Erreur interne \n )
    -[#red]-> Oui ;
    -Retour du code erreur \n **500: INTERNAL_ERROR**
    stop
    endif
}

partition "Creation de \nl'enrichissement" {
    -Génération du BEYONDID et du REVISIONID
    -Création de l'enrichissement \n templateId \n templateLabel \n idcardId \n idcardRevisionId \n Propriétaire \n ...;
    if ( \n Ecriture OK \n )
    -[#green]-> Oui ;
    -Retour du code \n **200: SUCCESS**
    else
    -[#red]-> Non ;
    -Retour du code erreur \n **500: INTERNAL_ERROR**
    endif
}
stop

legend 
**Légende**

**Retour du code erreur** : Permet la remontée d'un message d'erreur (localisée) à l'utilisateur.

endlegend

@enduml
