@startuml idcard_delete

title

Beyond Datafactory : Supprimer un idcard

end title

|#AntiqueWhite| Front |
start
->  **Hypothèse:** \n  - Utilisateur authentifié \n  - Profil Utilisateur BEYOND:  \n    - admin\n    - accéder;

-Être sur Datafactory\nOuverture de l'interface idcard
-Sélectionner l'idcard que l'on veut supprimer, en cliquant sur l'icône **info (i)** \nUne sidebar apparait à droite détaillant l'idcard\n\nCliquer sur le bouton **Poubelle** en haut à droite \n\nUne popup de confirmation apparait, valider avec \nle bouton "**Suppimer**"

| Back |
note right
  api "DELETE **/idcard/:id**"
end note
if ( \n Vérifier les droits \n **admin** \n)
-[#red]-> Non ;
-Retour du code erreur \n **401: UNAUTHORIZED**
stop
elseif ( \n ID valide \n )
-[#red]-> Non ;
-Retour du code erreur \n **406: ID_NOTVALID**
stop
endif

partition "Suppression de \nl'idcard" {
    -Suppression de l'enrichissement associé
    floating note left: Hard delete
    if ( \n fichier associé \n )
    -[#red]-> Oui;
    -Supprimer les fichiers dans le \nCOS (Cloud Object Storage)
    endif
    -Suppression de l'idcard
    if ( \n Ecriture OK \n )
    -[#green]-> Oui ;
    -Retour du code \n **200: SUCCESS**
    else
    -[#red]-> Non ;
    -Retour du code erreur \n **500: INTERNAL_ERROR**
    endif
}
stop

note right
  Doit-on supprimer l'idcard dans les associations ?
end note

legend 
**Légende**

**Retour du code erreur** : Permet la remontée d'un message d'erreur (localisé) à l'utilisateur.

endlegend

@enduml
