@startuml

title
POST **/idcard/** : Créer un idcard
Utiliser juste après une transformation

end title

start
note
**Amélioration**:
Vérifier les droits d'accès au service
endnote
if ( \n Valide body \n **JSON Schema** \n )
    -[#red]-> Non ;
    -Retour du code erreur \n **406: BODY_ERROR**
    stop
endif


partition "Creation de \nl'idcard" {
    -Génération du BEYONTID et du REVISIONID
    -Mise à jour de l'idcard de l'idcard
    if ( \n Ecriture OK \n )
        -[#green]-> Oui ;
        -Retour du code \n **200: SUCCESS**
    else
        -[#red]-> Non ;
        -Retour du code erreur \n **500: INTERNAL_ERROR**
    endif
}
stop

legend 
**Légende**

**Retour du code erreur** : Permet la remontée d'un message d'erreur (localisée) à l'utilisateur.

endlegend

@enduml
