@startuml

title
GET **/idcard/:id** : Récupérer un idcard

end title

start
if ( \n Vérifier les droits \n **access** \n)
-[#red]-> Non ;
-Retour du code erreur \n **401: UNAUTHORIZED**
stop
elseif ( \n Id Valide \n )
-[#red]-> Non ;
-Retour du code erreur \n **406: ID_NOTVALID**
stop
endif


partition "GetById " {
    -Récupère l'idcard
    note right
    **Amélioration**: 
    Vérifier le groupe de l'utilisateur pour ne remonter 
    uniquement l'idcard pour son groupe ou en public
    endnote
    if ( \n Données \n )
        -[#green]-> Oui ;
        -Retour du code \n **200: SUCCESS** \n avec la donnée
    elseif ( \n Erreur \n )
        -[#green]-> Non ;
        -Retour du code \n **400: NOT_FOUND**
    else
        -[#red]-> Oui ;
        -Retour du code erreur \n **500: INTERNAL_ERROR**
    endif
}
stop

legend 
**Légende**

**Retour du code erreur** : Permet la remontée d'un message d'erreur (localisé) à l'utilisateur.

endlegend

@enduml
