@startuml

title
GET **/idcard/** : Récupérer tous les idcards

end title

start
if ( \n Vérifier les droits \n **access** \n)
-[#red]-> Non ;
-Retour du code erreur \n **401: UNAUTHORIZED**
stop
endif


partition "GetAll " {
    -Récupère tous les idcards \npublics et du groupe de l'utilisateur
    note right
    en fonction
    * de la pagination
    * du tri
    * de la recherche
    endnote

    if ( \n Données \n )
        -[#green]-> Oui ;
        -Retour du code \n **200: SUCCESS** \n avec la donnée
    elseif ( \n Erreur sur la Query \n )
        -[#red]-> Oui ;
        -Retour du code erreur \n **404: QUERY_ERROR**
    else
        -[#red]-> Non ;
        -Retour du code erreur \n **500: INTERNAL_ERROR**
    endif
}
stop



legend 
**Légende**

**Retour du code erreur** : Permet la remontée d'un message d'erreur (localisé) à l'utilisateur.

endlegend

@enduml
