@startuml
actor Client
participant "User\nNotification" as Notif order 1
participant Integration order 2
participant "IDcard\nManager" as IDcard order 3
participant Keycloack order 4
participant IDP order 5
participant "User\nManagement" as UsrMngt order 6
collections "Buckets\n(COS)" as COS order 7
database MongoDB order 8
participant "Transformation\nAPI" as TrApi order 9
collections "Async. Queues\n(Rabbit MQ)" as Rabbit order 10
participant "Transfo. Service\n(Kubernetes)" as K8S order 11
Client -> Integration : initiate upload
activate Integration #888888
group Authentification, may have already taken place
Integration -> Keycloack : auth.
Keycloack -> Client : SSO
Client -> IDP : redirect
IDP -> Client : id / prod
Client -> IDP : submit id
IDP --> Keycloack : ok
Keycloack --> Integration : ok
end
Integration -> UsrMngt : check user rights
activate UsrMngt #888888
UsrMngt -> Integration : return rights (transfo A, B, ...)
deactivate UsrMngt
Integration -> Client : form to insert file
Client -> Integration : upload file + transfo X
Integration -> COS : PUT file [RAW BUCKET]
activate COS #888888
COS --> Integration : ok
deactivate COS
Integration -> IDcard : ask IDcard
activate IDcard #888888
IDcard -> MongoDB : create IDcard
activate MongoDB #888888
MongoDB --> IDcard : ok
deactivate MongoDB
IDcard --> Integration : ok
deactivate IDcard
Integration --> Notif : file received
Integration -> TrApi : ask Job(IDcard + transfo X)
activate TrApi #888888
TrApi -> Rabbit : JOB(X) request
activate Rabbit #888888
TrApi --> Integration : job submitted
Integration --> Notif : Transfo X running
Rabbit -> K8S : Call service X
activate K8S #888888
K8S -> COS : PUT file(s) [X BUCKET]
activate COS #888888
COS --> K8S : ok
deactivate COS
K8S -> Rabbit : Job DONE message
deactivate K8S
TrApi -> Rabbit : check queue (pub/sub)
deactivate Rabbit
TrApi -> IDcard : ask IDcard
activate IDcard #888888
IDcard -> MongoDB : create IDcard
activate MongoDB #888888
MongoDB --> IDcard : ok
deactivate MongoDB
IDcard --> TrApi : ok
deactivate IDcard
TrApi --> Integration : Job DONE
deactivate TrApi
Integration --> Notif : Transfo X done
deactivate Integration
@enduml
