version: '2.1'
services:
  geoserver:
    image: fred/geoserver:2.14.0
    volumes:
      - /Users/fchouteau/Documents/lot5-hyperviseur/DevelopperToolKit/04-GeoServer/Dockerfile/geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8680:8080"
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3