apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyp-app-postgis-deploy
  labels:
    app: hyp-app-postgis
spec:
  # The number of Pods
  replicas: 1
  # The number of old ReplicaSets to retain to allow rollback
  revisionHistoryLimit: 2
  template:
    metadata:
      name: hyp-app-postgis-pod
      labels:
        app: hyp-app-postgis
    spec:
      containers:
      - name: hyp-postgis-container
        image: registry.eu-de.bluemix.net/hyperviseurnspc/postgis:10.0-2.4
        env: # TODO dans secret
        - name: POSTGRES_DB
          value: "sixensegis"
        - name: POSTGRES_USER
          value: "docker"
        - name: POSTGRES_PASS
          value: "G5%s1D"
        - name: ALLOW_IP_RANGE
          value: "0.0.0.0/0"
        ports:
        - name: postgre-port
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: hyp-app-postgis-data
      imagePullSecrets:
      - name: bluemix-hypnspdev-secret
      volumes:
      - name: hyp-app-postgis-data
        persistentVolumeClaim:
          claimName: hyp-app-postgis-pvc-dev
